const teamFlagCodes: Record<string, string> = {
  ALEMANIA: "de",
  GERMANY: "de",
  "ARABIA SAUDITA": "sa",
  "SAUDI ARABIA": "sa",
  ARGELIA: "dz",
  ALGERIA: "dz",
  ARGENTINA: "ar",
  AUSTRALIA: "au",
  AUSTRIA: "at",
  BELGICA: "be",
  BELGIUM: "be",
  "BOSNIA Y HERZEG": "ba",
  "BOSNIA AND HERZEGOVINA": "ba",
  BRASIL: "br",
  BRAZIL: "br",
  "CABO VERDE": "cv",
  "CAPE VERDE": "cv",
  CANADA: "ca",
  CATAR: "qa",
  QATAR: "qa",
  COLOMBIA: "co",
  "COREA DEL SUR": "kr",
  "SOUTH KOREA": "kr",
  "COSTA DE MARFIL": "ci",
  "IVORY COAST": "ci",
  CROACIA: "hr",
  CROATIA: "hr",
  CURAZAO: "cw",
  CURACAO: "cw",
  ECUADOR: "ec",
  EGIPTO: "eg",
  EGYPT: "eg",
  ESCOCIA: "gb-sct",
  SCOTLAND: "gb-sct",
  ESPANA: "es",
  SPAIN: "es",
  "ESTADOS UNIDOS": "us",
  "UNITED STATES": "us",
  FRANCIA: "fr",
  FRANCE: "fr",
  GHANA: "gh",
  HAITI: "ht",
  INGLATERRA: "gb-eng",
  ENGLAND: "gb-eng",
  IRAK: "iq",
  IRAQ: "iq",
  IRAN: "ir",
  JAPON: "jp",
  JAPAN: "jp",
  JORDANIA: "jo",
  JORDAN: "jo",
  MARRUECOS: "ma",
  MOROCCO: "ma",
  MEXICO: "mx",
  NORUEGA: "no",
  NORWAY: "no",
  "NUEVA ZELANDA": "nz",
  "NEW ZEALAND": "nz",
  "PAISES BAJOS": "nl",
  NETHERLANDS: "nl",
  PANAMA: "pa",
  PARAGUAY: "py",
  PORTUGAL: "pt",
  "REP CHECA": "cz",
  "CZECH REPUBLIC": "cz",
  CZECHIA: "cz",
  "REP DEL CONGO": "cd",
  "DEMOCRATIC REPUBLIC OF THE CONGO": "cd",
  "CONGO DR": "cd",
  SENEGAL: "sn",
  SUDAFRICA: "za",
  "SOUTH AFRICA": "za",
  SUECIA: "se",
  SWEDEN: "se",
  SUIZA: "ch",
  SWITZERLAND: "ch",
  TUNEZ: "tn",
  TUNISIA: "tn",
  TURQUIA: "tr",
  TURKIYE: "tr",
  TURKEY: "tr",
  URUGUAY: "uy",
  UZBEKISTAN: "uz",
};

export function normalizeTeamName(name: string) {
  return name
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .replace(/\./g, "")
    .replace(/\s+/g, " ")
    .trim()
    .toUpperCase();
}

export function flagUrlForTeam(name?: string | null) {
  if (!name) return null;
  const code = teamFlagCodes[normalizeTeamName(name)];
  return code ? `https://flagcdn.com/${code}.svg` : null;
}
